-- Post에 카운트 컬럼 (이미 있으면 생략)
ALTER TABLE post
  ADD COLUMN IF NOT EXISTS like_count INT DEFAULT 0 NOT NULL;

ALTER TABLE post
  ADD COLUMN IF NOT EXISTS dislike_count INT DEFAULT 0 NOT NULL;


-- PostReaction 테이블 (이미 있으면 생략 조건은 DB별 차이)
CREATE TABLE IF NOT EXISTS post_reaction (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     BIGINT NOT NULL,
  user_id     BIGINT NOT NULL,
  type        VARCHAR(8) NOT NULL,
  created_at  TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP NOT NULL,

  CONSTRAINT uk_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_post_reaction_post  ON post_reaction(post_id);
CREATE INDEX IF NOT EXISTS ix_post_reaction_user  ON post_reaction(user_id);
CREATE INDEX IF NOT EXISTS ix_post_reaction_type  ON post_reaction(type);